services:
  backend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db-bic2:5432/mydatabase
      - JWT_SECRET=your_jwt_secret_key
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    ## Si --watch ne fonctionne pas sur votre système, utilisez nodemon
    #command: sh -c "npm install && npm run dev:nodemon"
    depends_on:
      - db-bic2

  db-bic2:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - bic2-db-data:/var/lib/postgresql/data

  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  bic2-db-data:
