GET http://localhost:3000/?name=John&age=30

###
POST http://localhost:3000/
Content-Type: application/json

{
  "name": "Jane",
  "age": 25
}

###
POST http://localhost:3000/
Content-Type: application/x-www-form-urlencoded

name=Jane&age=25

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTA3NjYxNTQtYTJlNC00ZDNkLWJmZGMtZWU0ZmVhMmExODgyIiwibmFtZSI6IkphbmUgRG9lIiwiaWF0IjoxNzU5NzQxMzA1fQ.k2yKCdjx39hsZGs3eFf32yFjrps_c_BZ2NRPU_xKrM0

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "t@t.com",
  "password": "password123",
  "name": "Jane",
  "age": 25
}

###
GET http://localhost:3000/users/1759252031812

###
PATCH http://localhost:3000/users/10766154-a2e4-4d3d-bfdc-ee4fea2a1882
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTA3NjYxNTQtYTJlNC00ZDNkLWJmZGMtZWU0ZmVhMmExODgyIiwibmFtZSI6IkphbmUgRG9lIiwiaWF0IjoxNzU5NzQxMzA1fQ.k2yKCdjx39hsZGs3eFf32yFjrps_c_BZ2NRPU_xKrM0

{
  "name": "Jane Doe",
  "password": "newpassword456",
  "role": "ADMIN"
}

###
DELETE http://localhost:3000/users/1759252031812

###
GET http://localhost:3000/articles

###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "New Article",
  "content": "This is the content of the new article."
}

###
GET http://localhost:3000/articles/8b6c5400-63a0-4d9b-8a00-45234bcf89d7

###
PATCH http://localhost:3000/articles/976087ee-de03-43bf-b44a-ac5702caa5aa
Content-Type: application/json

{
  "status": "PUBLISHED"
}

###
DELETE http://localhost:3000/articles/8b6c5400-63a0-4d9b-8a00-45234bcf89d7

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "t@t.com",
  "password": "newpassword456"
}