GET http://localhost:3000/?activated=true

###
POST http://localhost:3000
Content-Type: application/json

{
    "username": "testuser",
    "email": "testuser@example.com"
}

###
POST http://localhost:3000
Content-Type: application/x-www-form-urlencoded

username=testuser&email=testuser@example.com

###
POST http://localhost:3000
Content-Type: application/xml

<user>
    <username>testuser</username>
    <email>testuser@example.com</email>
</user>

###
GET http://localhost:3000/users

### => RETURN 422
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "newuser",
    "email": "newuser@example.com"
}

### => 
POST http://localhost:3000/users
Content-Type: application/json

{
    "login": "newuse3",
    "email": "newuser3@example.com",
    "password": "securepassword"
}
### =>
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "login": "really hashed password"
}
###
GET http://localhost:3000/categories

### => RETURN 422
POST http://localhost:3000/categories
Content-Type: application/json

{
    "categoriename": "newcategorie",
    "email": "newcategorie@example.com"
}

### => 
POST http://localhost:3000/categories
Content-Type: application/json

{
    "title": "newuse1"
}
### => 
PATCH http://localhost:3000/categories/2
Content-Type: application/json

{
    "title": "category updated 5",
    "description": "category updated 5"
}
### => 
POST http://localhost:3000/categories
Content-Type: application/json

{
    "title": "newuse1",
    "description": "This is a new category"
}
###
GET http://localhost:3000/labels

### => RETURN 422
POST http://localhost:3000/labels
Content-Type: application/json

{
    "categoriename": "newcategorie",
    "email": "newcategorie@example.com"
}

### => 
POST http://localhost:3000/labels
Content-Type: application/json

{
    "title": "newuse1"
}
### => 
POST http://localhost:3000/labels
Content-Type: application/json

{
    "title": "newuse1",
    "description": "This is a new category"
}


### 
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "newuser3@example.com",
    "password": "securepassword"
}